//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class FavoriteAttraction
    {
        public int FavoriteAttractionId { get; set; }
        public Nullable<int> AttractionId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> FavoriteAttractionRate { get; set; }
    
        public virtual Attraction Attraction { get; set; }
        public virtual Users Users { get; set; }
    }
}
