//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int MessageId { get; set; }
        public Nullable<System.DateTime> MessageDateTime { get; set; }
        public string MessageDetails { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> AttractionId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> AccessLevelId { get; set; }
    
        public virtual AccessLevel AccessLevel { get; set; }
        public virtual Attraction Attraction { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Users Users { get; set; }
    }
}
