//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class QueuePerUser
    {
        public int QueuePerUserId { get; set; }
        public int QueueId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> CountTickets { get; set; }
    
        public virtual Queues Queues { get; set; }
        public virtual Users Users { get; set; }
    }
}
